Makefile
a.txt
builtin.c
builtin_detect.c
builtin_detect.o
builtin_echo.c
builtin_echo.o
builtin_exit.c
builtin_exit.o
builtin_pwd_cd.c
builtin_pwd_cd.o
deeeneme
deneke
exec_execve.c
exec_execve.o
exec_heredoc.c
exec_starter.c
exec_starter.o
executable_redirection.c
executable_redirection.o
executable_struct.c
executable_struct.o
libft
main.c
main.o
mert.c
minishell
minishell.h
parser_categorize.c
parser_categorize.o
parser_for_quotes.c
parser_for_quotes.o
parser_get_tokens_2.c
parser_get_tokens_2.o
parser_get_tokens_main.c
parser_get_tokens_main.o
parser_init_and_free.c
parser_init_and_free.o
parser_utils.c
parser_utils.o
utils.c
utils.o
utils_str.c
utils_str.o
yazdirmafonksiyonları.c
